# Generated by Django 6.0.6 on 2026-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("img", models.URLField(max_length=500)),
                ("tipoArt", models.CharField(max_length=100)),
                ("privado", models.BooleanField(default=False)),
            ],
        ),
    ]
